version: '3'

services:
  crud_mysql:
    container_name: medine-crud-mysql
    image: mariadb:10.6
    ports:
      - "3361:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=medine03.
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=medine03.", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  crud_php:
    container_name: medine-crud-php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8041:8040"
      - "9041:9001"
    volumes:
      - .:/app:delegated
    command: php -S 0.0.0.0:8040 -t /app
